In [310]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print('setup complete')

setup complete

In [311]:
gender_submission = pd.read_csv("../Data/titanic/gender_submission.csv", index_col = 0)
gender_submission

             Survived
PassengerId
892                 0
893                 1
...               ...
1308                0
1309                0

[418 rows x 1 columns]

In [312]:
test = pd.read_csv("../Data/titanic/test.csv")
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [313]:
train = pd.read_csv("../Data/titanic/train.csv")
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [314]:
def Fare(row):
    if row.Fare >= 30.00:
        return row.Fare
    else:
        return 'Less than 30'

fare_above_30 = train.apply(Fare, axis = 'columns')
fare_above_30.head()

0    Less than 30
1         71.2833
2    Less than 30
3            53.1
4    Less than 30
dtype: object

In [315]:
gender_submission1 = gender_submission.Survived == 1
gender_submission1

PassengerId
892     False
893      True
        ...
1308    False
1309    False
Name: Survived, Length: 418, dtype: bool

In [316]:
train.Sex.apply(lambda x: "Male" if x == 'male' else 'female')

0        Male
1      female
        ...
889      Male
890      Male
Name: Sex, Length: 891, dtype: str

In [317]:
train.Sex.map({'male':0, 'female':1})

0      0
1      1
      ..
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [318]:
test.describe()

       PassengerId     Pclass        Age       SibSp       Parch        Fare
count       418.00  418.00000  332.00000  418.000000  418.000000  417.000000
mean       1100.50    2.26555   30.27259    0.447368    0.392344   35.627188
...            ...        ...        ...         ...         ...         ...
75%        1204.75    3.00000   39.00000    1.000000    0.000000   31.500000
max        1309.00    3.00000   76.00000    8.000000    9.000000  512.329200

[8 rows x 6 columns]

In [319]:
test.Cabin.isnull().sum()

np.int64(327)

In [320]:
pd.pivot_table(test, values=['Age','Fare'], index = ['PassengerId','Name','Sex'], columns = ['Embarked'] ).fillna('N/A').head()

                                                                 Age        \
Embarked                                                           C     Q
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male    N/A  34.5
893         Wilkes, Mrs. James (Ellen Needs)             female  N/A   N/A
894         Myles, Mr. Thomas Francis                    male    N/A  62.0
895         Wirz, Mr. Albert                             male    N/A   N/A
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female  N/A   N/A

                                                                      Fare  \
Embarked                                                            S    C
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male     N/A  N/A
893         Wilkes, Mrs. James (Ellen Needs)             female  47.0  N/A
894         Myles, Mr. Thomas Francis                    male     N/A  N/A
895         Wirz, Mr. Albert                             male    27.0  N/A
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female  22.0  N/A

                                                                         \
Embarked                                                              Q
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male    7.8292
893         Wilkes, Mrs. James (Ellen Needs)             female     N/A
894         Myles, Mr. Thomas Francis                    male    9.6875
895         Wirz, Mr. Albert                             male       N/A
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female     N/A


Embarked                                                               S
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male        N/A
893         Wilkes, Mrs. James (Ellen Needs)             female      7.0
894         Myles, Mr. Thomas Francis                    male        N/A
895         Wirz, Mr. Albert                             male     8.6625
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female  12.2875

In [321]:
test.Cabin.fillna('Unknown')

0      Unknown
1      Unknown
        ...
416    Unknown
417    Unknown
Name: Cabin, Length: 418, dtype: str

In [322]:
test.Age.unique()

array([34.5 , 47.  , 62.  , 27.  , 22.  , 14.  , 30.  , 26.  , 18.  ,
       21.  ,   nan, 46.  , 23.  , 63.  , 24.  , 35.  , 45.  , 55.  ,
        9.  , 48.  , 50.  , 22.5 , 41.  , 33.  , 18.5 , 25.  , 39.  ,
       60.  , 36.  , 20.  , 28.  , 10.  , 17.  , 32.  , 13.  , 31.  ,
       29.  , 28.5 , 32.5 ,  6.  , 67.  , 49.  ,  2.  , 76.  , 43.  ,
       16.  ,  1.  , 12.  , 42.  , 53.  , 26.5 , 40.  , 61.  , 60.5 ,
        7.  , 15.  , 54.  , 64.  , 37.  , 34.  , 11.5 ,  8.  ,  0.33,
       38.  , 57.  , 40.5 ,  0.92, 19.  , 36.5 ,  0.75,  0.83, 58.  ,
        0.17, 59.  , 14.5 , 44.  ,  5.  , 51.  ,  3.  , 38.5 ])

In [323]:
train['newCol'] = train.apply(lambda p: p['SibSp'] + p['Parch'], axis = 1)
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,newCol
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [324]:

def Fare_class(row):
    if pd.isna(row['Fare']):
        return 'unknown'
    elif row['Fare'] >= 50:
        return 'High Fare'
    else:
        return 'low Fare'
Fare_classes = train.apply(Fare_class, axis = 1).head()
Fare_classes

0     low Fare
1    High Fare
2     low Fare
3    High Fare
4     low Fare
dtype: str

In [325]:
test.Fare.isnull().sum()

np.int64(1)

In [326]:
train['Embarked'] = train.Embarked.map({'S':'Southamperg', 'C':'Cherbourg', 'Q':'Queenstown'})
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,newCol
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,Southamperg,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,Cherbourg,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,Cherbourg,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Queenstown,0

In [327]:
train.Pclass.unique().dtype

dtype('int64')

In [328]:
train.Pclass.fillna('Unknown')

0      3
1      1
      ..
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [329]:
train['Pclass'] = train.Pclass.map({ 1 :'One', 2 : 'second', 3 : 'third'})

In [330]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,newCol
0,1,0,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,Southamperg,1
1,2,1,One,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,Cherbourg,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,One,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,Cherbourg,0
890,891,0,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Queenstown,0

In [331]:
train.pivot_table(values='Fare', index='Pclass', columns='Age', aggfunc='mean') #average fare per Pclass and age //can be done with other columns

Age,0.42,0.67,0.75,0.83,0.92,1.00,2.00,3.00,4.00,5.00,...,62.00,63.00,64.00,65.00,66.00,70.00,70.50,71.00,74.00,80.00
Pclass,,,,,,,,,,,,,,,,,,,,,
One,NaN,NaN,NaN,NaN,151.55,NaN,151.550000,NaN,81.858300,NaN,...,44.366667,77.9583,144.5,44.2646,NaN,71.0,NaN,42.0792,NaN,30.0
second,NaN,14.5,NaN,23.875,NaN,38.0021,26.000000,28.7764,31.000000,27.750000,...,10.500000,NaN,NaN,NaN,10.5,10.5,NaN,NaN,NaN,NaN
third,8.5167,NaN,19.2583,NaN,NaN,26.8075,24.544643,22.7875,21.653571,21.040267,...,NaN,9.5875,NaN,7.7500,NaN,NaN,7.75,NaN,7.775,NaN

In [332]:
train.pivot_table(values='Survived', index='Pclass', columns='Sex', aggfunc='mean')

Sex       female      male
Pclass
One     0.968085  0.368852
second  0.921053  0.157407
third   0.500000  0.135447

In [333]:
train.pivot_table(values='Survived', index='Embarked', columns='Pclass', aggfunc='sum')

Pclass       One  second  third
Embarked
Cherbourg     59       9     25
Queenstown     1       2     27
Southamperg   74      76     67

In [334]:
train.pivot_table(values='newCol', index= 'Pclass', columns='Survived', aggfunc='sum')

Survived    0    1
Pclass
One        47  120
second     45   99
third     393  102

In [335]:
train.pivot_table(values='Fare', index='Pclass', columns='Embarked', aggfunc='median')

Embarked  Cherbourg  Queenstown  Southamperg
Pclass
One         78.2667       90.00        52.00
second      24.0000       12.35        13.50
third        7.8958        7.75         8.05

In [336]:
train.pivot_table(values='Fare', index='Pclass', columns='Embarked', aggfunc='mean')

Embarked   Cherbourg  Queenstown  Southamperg
Pclass
One       104.718529   90.000000    70.364862
second     25.358335   12.350000    20.327439
third      11.214083   11.183393    14.644083

In [337]:
test['Age_groups'] = pd.cut(test['Age'], bins=[0,10,45,90], labels=['Young', 'Adult', 'Old'])
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_groups
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Adult
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Old
...,...,...,...,...,...,...,...,...,...,...,...,...
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,NaN
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,NaN

In [338]:
test.Fare.loc[test.Fare > 400]

343    512.3292
Name: Fare, dtype: float64

In [339]:
test['Fare_class'] = pd.cut(test.Fare, bins=[0,50,100,200,300,515], labels=['budget','economy','premium','luxury','royalty'])
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_groups,Fare_class
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Adult,budget
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Old,budget
...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,NaN,budget
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,NaN,budget

In [340]:
test.Fare_class.loc[test.Fare_class == 'royalty']

343    royalty
Name: Fare_class, dtype: category
Categories (5, str): ['budget' < 'economy' < 'premium' < 'luxury' < 'royalty']

In [341]:
test.Fare_class.loc[test.Fare_class == 'luxury']

24     luxury
53     luxury
        ...
375    luxury
407    luxury
Name: Fare_class, Length: 17, dtype: category
Categories (5, str): ['budget' < 'economy' < 'premium' < 'luxury' < 'royalty']

In [342]:
train.newCol.max()

np.int64(10)

In [343]:
train['Family_class'] = pd.cut(train.newCol, bins= [0,1,5,10], labels=['Solo', 'Small', 'large'])
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,newCol,Family_class
0,1,0,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,Southamperg,1,Solo
1,2,1,One,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,Cherbourg,1,Solo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,One,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,Cherbourg,0,NaN
890,891,0,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Queenstown,0,NaN

In [344]:
train.Family_class.loc[train.Family_class == 'large']

13     large
25     large
       ...
850    large
863    large
Name: Family_class, Length: 25, dtype: category
Categories (3, str): ['Solo' < 'Small' < 'large']

In [345]:
#equal-width fare bands across all passengers
train.Fare_bands = pd.cut(train.Fare, bins=5)
train.Fare_bands

C:\Users\LOQ\AppData\Local\Temp\ipykernel_6060\688399039.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  train.Fare_bands = pd.cut(train.Fare, bins=5)

0      (-0.512, 102.466]
1      (-0.512, 102.466]
             ...
889    (-0.512, 102.466]
890    (-0.512, 102.466]
Name: Fare, Length: 891, dtype: category
Categories (5, interval[float64, right]): [(-0.512, 102.466] < (102.466, 204.932] < (204.932, 307.398] < (307.398, 409.863] < (409.863, 512.329]]

In [346]:
train.decade_groups = pd.cut(train.Age, bins= range(0,110,10), labels=['0s','10s','20s','30s','40s','50s','60s','70s','80s','90s'])
train.decade_groups

C:\Users\LOQ\AppData\Local\Temp\ipykernel_6060\234267973.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  train.decade_groups = pd.cut(train.Age, bins= range(0,110,10), labels=['0s','10s','20s','30s','40s','50s','60s','70s','80s','90s'])

0      20s
1      30s
      ...
889    20s
890    30s
Name: Age, Length: 891, dtype: category
Categories (10, str): ['0s' < '10s' < '20s' < '30s' ... '60s' < '70s' < '80s' < '90s']

In [347]:
#convert a wide summary table of average Age and Fare per class into long format
wide = test.groupby('Pclass')[['Age', 'Fare']].mean().reset_index()
wide

   Pclass        Age       Fare
0       1  40.918367  94.280297
1       2  28.777500  22.202104
2       3  24.027945  12.459678

In [348]:
long = wide.melt(id_vars='Pclass', var_name='Metric', value_name='Average')
long

    Pclass Metric    Average
0        1    Age  40.918367
1        2    Age  28.777500
..     ...    ...        ...
4        2   Fare  22.202104
5        3   Fare  12.459678

[6 rows x 3 columns]

In [349]:
long0 = test[['PassengerId', 'SibSp', 'Parch']].melt(id_vars='PassengerId', var_name='Relatives', value_name='Comb_count') 
#combine SibSp and Parch into a single column in long format
long0

     PassengerId Relatives  Comb_count
0            892     SibSp           0
1            893     SibSp           1
..           ...       ...         ...
834         1308     Parch           0
835         1309     Parch           1

[836 rows x 3 columns]

In [350]:
#qn: how many people are over 50 years old
(train.Age > 50).sum()

np.int64(64)

In [351]:
#survival rate by sex
Total = train.groupby('Sex')['Survived'].count() #it counts the total no. of both genders bc, both 0 and 1 are not null values
Total

Sex
female    314
male      577
Name: Survived, dtype: int64

In [352]:
survived = train.query('Survived == 1').groupby('Sex')['Survived'].count() #this only counts the values of '1' in 'Survived' thus giving the no. of only survived people in each gender
rate_of_survival = survived / Total
rate_of_survival

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [353]:
#survival rate by class
PclassTotal = train.groupby('Pclass')['Survived'].count()
PclassTotal

Pclass
One       216
second    184
third     491
Name: Survived, dtype: int64

In [354]:
Pclass_survived = train.query('Survived == 1').groupby('Pclass')['Survived'].count()
Pclass_survived

Pclass
One       136
second     87
third     119
Name: Survived, dtype: int64

In [355]:
rate_by_Pclass = Pclass_survived / PclassTotal
rate_by_Pclass

Pclass
One       0.629630
second    0.472826
third     0.242363
Name: Survived, dtype: float64

In [356]:
#avg age of survivors vs non survivors
avg_survivors = train.query('Survived == 1').groupby('Survived')['Age'].mean()
avg_survivors

Survived
1    28.34369
Name: Age, dtype: float64

In [357]:
avg_died = train.query('Survived == 0').groupby('Survived')['Age'].mean()
avg_died

Survived
0    30.626179
Name: Age, dtype: float64

In [358]:
avg_age = train.groupby('Survived').Age.mean()
avg_age

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

In [359]:
#which embarkment point had the highest survival rate
total_embarkment = train.groupby('Embarked')['Survived'].count()
total_embarkment

Embarked
Cherbourg      168
Queenstown      77
Southamperg    644
Name: Survived, dtype: int64

In [360]:
survived_by_embarkment = train.query('Survived == 1').groupby('Embarked')['Survived'].count()
survived_by_embarkment

Embarked
Cherbourg       93
Queenstown      30
Southamperg    217
Name: Survived, dtype: int64

In [361]:
sorted_survival_by_embark = (survived_by_embarkment / total_embarkment).sort_values(ascending = False)

In [362]:
sorted_survival_by_embark

Embarked
Cherbourg      0.553571
Queenstown     0.389610
Southamperg    0.336957
Name: Survived, dtype: float64

In [363]:
#survival when travelling alone vs with family
total_family_survived = train.query('Survived == 1').groupby('Survived')['newCol'].count()
total_family_survived

Survived
1    342
Name: newCol, dtype: int64

In [364]:
solo_survived = train.query('newCol == 1 and Survived == 1').groupby('Survived')['newCol'].count()
solo_survived

Survived
1    89
Name: newCol, dtype: int64

In [365]:
family_survived = train.query('newCol > 1 and Survived == 1').groupby('Survived')['newCol'].count()
family_survived

Survived
1    90
Name: newCol, dtype: int64

In [366]:
solo_survival_rate = solo_survived / total_family_survived
solo_survival_rate

Survived
1    0.260234
Name: newCol, dtype: float64

In [367]:
family_survived_rate = family_survived / total_family_survived  
family_survived_rate

Survived
1    0.263158
Name: newCol, dtype: float64

In [368]:
family_survived_rate >solo_survival_rate

Survived
1    True
Name: newCol, dtype: bool

<i>Dataset:Titanic — [Kaggle](https://www.kaggle.com/c/titanic/data)</i>

<b>Practiced:</b> apply()  map()  pivot_table()  cut()  melt() query()

<b>Questions answered by code:</b>
Survival rate by gender<br>
survival rate by class<br>
Average age survived vs died<br>
Survival rate by embark<br>
Alone vs family did it affect survival?<br>