In [73]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print('setup complete')

setup complete

In [74]:
gender_submission = pd.read_csv("../Data/titanic/gender_submission.csv", index_col = 0)
gender_submission

             Survived
PassengerId
892                 0
893                 1
...               ...
1308                0
1309                0

[418 rows x 1 columns]

In [89]:
test = pd.read_csv("../Data/titanic/test.csv")
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [113]:
train = pd.read_csv("../Data/titanic/train.csv")
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
...,...,...,...,...,...,...,...,...,...,...,...,...
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [77]:
def Fare(row):
    if row.Fare >= 30.00:
        return row.Fare
    else:
        return 'Less than 30'

fare_above_30 = train.apply(Fare, axis = 'columns')
fare_above_30.head()

PassengerId
1    Less than 30
2         71.2833
3    Less than 30
4            53.1
5    Less than 30
dtype: object

In [78]:
gender_submission1 = gender_submission.Survived == 1
gender_submission1

PassengerId
892     False
893      True
        ...
1308    False
1309    False
Name: Survived, Length: 418, dtype: bool

In [79]:
train.Sex.apply(lambda x: "Male" if x == 'male' else 'female')

PassengerId
1        Male
2      female
        ...
890      Male
891      Male
Name: Sex, Length: 891, dtype: str

In [80]:
train.Sex.map({'male':0, 'female':1})

PassengerId
1      0
2      1
      ..
890    0
891    0
Name: Sex, Length: 891, dtype: int64

In [81]:
test.describe()

          Pclass        Age       SibSp       Parch        Fare
count  418.00000  332.00000  418.000000  418.000000  417.000000
mean     2.26555   30.27259    0.447368    0.392344   35.627188
...          ...        ...         ...         ...         ...
75%      3.00000   39.00000    1.000000    0.000000   31.500000
max      3.00000   76.00000    8.000000    9.000000  512.329200

[8 rows x 5 columns]

In [104]:
test.Cabin.isnull().sum()

np.int64(327)

In [112]:
pd.pivot_table(test, values=['Age','Fare'], index = ['PassengerId','Name','Sex'], columns = ['Embarked'] ).fillna('N/A').head()

                                                                 Age        \
Embarked                                                           C     Q
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male    N/A  34.5
893         Wilkes, Mrs. James (Ellen Needs)             female  N/A   N/A
894         Myles, Mr. Thomas Francis                    male    N/A  62.0
895         Wirz, Mr. Albert                             male    N/A   N/A
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female  N/A   N/A

                                                                      Fare  \
Embarked                                                            S    C
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male     N/A  N/A
893         Wilkes, Mrs. James (Ellen Needs)             female  47.0  N/A
894         Myles, Mr. Thomas Francis                    male     N/A  N/A
895         Wirz, Mr. Albert                             male    27.0  N/A
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female  22.0  N/A

                                                                         \
Embarked                                                              Q
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male    7.8292
893         Wilkes, Mrs. James (Ellen Needs)             female     N/A
894         Myles, Mr. Thomas Francis                    male    9.6875
895         Wirz, Mr. Albert                             male       N/A
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female     N/A


Embarked                                                               S
PassengerId Name                                         Sex
892         Kelly, Mr. James                             male        N/A
893         Wilkes, Mrs. James (Ellen Needs)             female      7.0
894         Myles, Mr. Thomas Francis                    male        N/A
895         Wirz, Mr. Albert                             male     8.6625
896         Hirvonen, Mrs. Alexander (Helga E Lindqvist) female  12.2875

In [105]:
test.Cabin.fillna('Unknown')

0      Unknown
1      Unknown
        ...
416    Unknown
417    Unknown
Name: Cabin, Length: 418, dtype: str

In [116]:
test.Age.unique()

array([34.5 , 47.  , 62.  , 27.  , 22.  , 14.  , 30.  , 26.  , 18.  ,
       21.  ,   nan, 46.  , 23.  , 63.  , 24.  , 35.  , 45.  , 55.  ,
        9.  , 48.  , 50.  , 22.5 , 41.  , 33.  , 18.5 , 25.  , 39.  ,
       60.  , 36.  , 20.  , 28.  , 10.  , 17.  , 32.  , 13.  , 31.  ,
       29.  , 28.5 , 32.5 ,  6.  , 67.  , 49.  ,  2.  , 76.  , 43.  ,
       16.  ,  1.  , 12.  , 42.  , 53.  , 26.5 , 40.  , 61.  , 60.5 ,
        7.  , 15.  , 54.  , 64.  , 37.  , 34.  , 11.5 ,  8.  ,  0.33,
       38.  , 57.  , 40.5 ,  0.92, 19.  , 36.5 ,  0.75,  0.83, 58.  ,
        0.17, 59.  , 14.5 , 44.  ,  5.  , 51.  ,  3.  , 38.5 ])